import fs from 'fs';

let content = fs.readFileSync('src/components/Orders/OrderForm.tsx', 'utf8');

const replacements = [
  ['Preencha os dados do pedido', "{t('orders.form.fillOrderData')}"],
  ['>\\s*Série\\s*<', ">{t('orders.table.serie')}<"],
  ['placeholder="Ex: 1"', "placeholder={t('orders.form.seriePlaceholder')}"],
  ['>\\s*Número do Pedido \\*\\s*<', ">{t('orders.form.orderNumber')}<"],
  ['placeholder="Ex: PED-2024-001"', "placeholder={t('orders.form.orderNumberPlaceholder')}"],
  ['>\\s*Código de Rastreamento\\s*<', ">{t('orders.form.trackingCode')}<"],
  ['placeholder="Gerado automaticamente"', "placeholder={t('orders.form.trackingCodeGenerated')}"],
  ['>\\s*Status \\*\\s*<', ">{t('orders.form.status')}<"],
  ['>Emitido<', ">{t('orders.statusOptions.issued')}<"],
  ['>Em Coleta<', ">{t('orders.statusOptions.collected')}<"],
  ['>Em Trânsito<', ">{t('orders.statusOptions.inTransit')}<"],
  ['>Saiu p/Entrega<', ">{t('orders.statusOptions.outForDelivery')}<"],
  ['>Entregue<', ">{t('orders.statusOptions.delivered')}<"],
  ['>Cancelado<', ">{t('orders.statusOptions.canceled')}<"],
  ['>\\s*Data de Emissão \\*\\s*<', ">{t('orders.form.issueDate')}<"],
  ['>\\s*Data de Entrada \\*\\s*<', ">{t('orders.table.entryDate')} *<"],
  ['>\\s*Previsão de Entrega\\s*<', ">{t('orders.table.expectedDate')}<"],
  ['>\\s*Transportadora\\s*<', ">{t('orders.form.carrier')}<"],
  ['>\\s*Observações\\s*<', ">{t('orders.form.observations')}<"],
  ['placeholder="Observações adicionais sobre o pedido..."', "placeholder={t('orders.form.obsPlaceholder')}"],
  ['<strong>Selecione um cliente existente</strong> ou preencha os dados manualmente abaixo.', "<span dangerouslySetInnerHTML={{ __html: t('orders.form.addCustomerMsg') }} />"],
  ['>\\s*Selecionar Cliente Cadastrado\\s*<', ">{t('orders.form.selectCustomerBtn')}<"],
  ['>\\s*Nenhum cliente encontrado\\s*<', ">{t('orders.form.noCustomersFound')}<"],
  ['>\\s*Nome / Razão Social \\*\\s*<', ">{t('orders.form.customerName')}<"],
  ['placeholder="Digite o nome do cliente"', "placeholder={t('orders.form.customerNamePlaceholder')}"],
  ['>\\s*CNPJ / CPF\\s*<', ">{t('orders.form.document')}<"],
  ['>\\s*Endereço\\s*<', ">{t('orders.form.address')}<"],
  ['placeholder="Rua, Avenida..."', "placeholder={t('orders.form.addressPlaceholder')}"],
  ['>\\s*Número\\s*<', ">{t('orders.form.number')}<"],
  ['>\\s*Complemento\\s*<', ">{t('orders.form.complement')}<"],
  ['placeholder="Apto, Sala, Bloco..."', "placeholder={t('orders.form.complementPlaceholder')}"],
  ['>\\s*Bairro\\s*<', ">{t('orders.form.neighborhood')}<"],
  ['placeholder="Centro"', "placeholder={t('orders.form.neighborhoodPlaceholder')}"],
  ['>\\s*Cidade \\*\\s*<', ">{t('orders.form.city')}<"],
  ['placeholder="São Paulo"', "placeholder={t('orders.form.cityPlaceholder')}"],
  ['>\\s*Estado \\*\\s*<', ">{t('orders.form.state')}<"],
  ['>Selecione o estado<', ">{t('orders.form.selectState')}<"],
  ['>\\s*CEP\\s*<', ">{t('orders.form.zipCode')}<"],
  ['>\\s*Telefone\\s*<', ">{t('orders.form.phone')}<"],
  ['>\\s*Email\\s*<', ">{t('orders.form.email')}<"],
  ['placeholder="cliente@email.com"', "placeholder={t('orders.form.emailPlaceholder')}"],
  ['>\\s*Adicione os itens deste pedido\\s*<', ">{t('orders.form.addProductsMsg')}<"],
  ['>\\s*Adicionar Item\\s*<', ">{t('orders.form.addProductBtn')}<"],
  ['>Nenhum item adicionado<', ">{t('orders.form.noProductsMsg')}<"],
  ['>Adicionar Primeiro Item<', ">{t('orders.form.addFirstProductBtn')}<"],
  ['>Código<', ">{t('orders.form.productCode')}<"],
  ['placeholder="Código"', "placeholder={t('orders.form.productCodePlaceholder')}"],
  ['>Descrição<', ">{t('orders.form.productDescription')}<"],
  ['placeholder="Descrição do item"', "placeholder={t('orders.form.productDescPlaceholder')}"],
  ['>Qtd<', ">{t('orders.form.quantity')}<"],
  ['>Peso \\(kg\\)<', ">{t('orders.form.weight')}<"],
  ['>Cubagem \\(m³\\)<', ">{t('orders.form.cubicMeters')}<"],
  ['>Valor Unit\\.<', ">{t('orders.form.unitPrice')}<"],
  ['>Valor Total<', ">{t('orders.form.totalPrice')}<"],
  ['title="Remover item"', "title={t('orders.form.removeItem')}"],
  ['>\\s*Total dos Itens:\\s*<', ">{t('orders.form.totalProductsValue')}<"],
  ['>\\s*Valor Total do Pedido\\s*<', ">{t('orders.form.orderTotalValue')}<"],
  ['>\\s*Valor dos Itens\\s*<', ">{t('orders.details.summary.itemsValue')}<"],
  ['>\\s*Valor do Frete Estimado\\s*<', ">{t('orders.form.freightEstimatedValue')}<"],
  ['>Será sobrescrito pelo cálculo automático se o peso for preenchido<', ">{t('orders.form.freightEstimatedHint')}<"],
  ['>Dados da Carga \\(para cálculo de frete automático\\)<', ">{t('orders.form.cargoDataHint')}<"],
  ['>\\s*Peso Total \\(kg\\)\\s*<', ">{t('orders.form.weight')}<"],
  ['>\\s*Quantidade de Volumes\\s*<', ">{t('orders.form.volumesQty')}<"],
  ['>Calculado automaticamente<', ">{t('orders.form.calculatedAutoHint')}<"],
  ['>Valor do Pedido \\(sem frete\\):<', ">{t('orders.form.orderValueWithoutFreight')}<"],
  ['>Valor do Frete:<', ">{t('orders.table.freightValue')}:<"],
  ['>Total Geral:<', ">{t('orders.form.totalGeneral')}<"]
];

replacements.forEach(([search, replace]) => {
  content = content.replace(new RegExp(search, 'g'), replace);
});

fs.writeFileSync('src/components/Orders/OrderForm.tsx', content);
console.log('OrderForm updated with RegEx!');
