-- Importação completa de países do mundo
-- Este script adiciona todos os países reconhecidos internacionalmente
-- Mantém os 10 países já existentes e adiciona os restantes

-- Inserir países da Europa
INSERT INTO countries (code, name, flag, continent, capital, language, bacen_code) VALUES
('DE', 'Alemanha', '🇩🇪', 'Europa', 'Berlim', 'Alemão', '0230'),
('AT', 'Áustria', '🇦🇹', 'Europa', 'Viena', 'Alemão', '0431'),
('BE', 'Bélgica', '🇧🇪', 'Europa', 'Bruxelas', 'Holandês/Francês', '0957'),
('BG', 'Bulgária', '🇧🇬', 'Europa', 'Sófia', 'Búlgaro', '1082'),
('HR', 'Croácia', '🇭🇷', 'Europa', 'Zagreb', 'Croata', '1392'),
('DK', 'Dinamarca', '🇩🇰', 'Europa', 'Copenhague', 'Dinamarquês', '1457'),
('SK', 'Eslováquia', '🇸🇰', 'Europa', 'Bratislava', 'Eslovaco', '1538'),
('SI', 'Eslovênia', '🇸🇮', 'Europa', 'Liubliana', 'Esloveno', '1546'),
('ES', 'Espanha', '🇪🇸', 'Europa', 'Madri', 'Espanhol', '1554'),
('EE', 'Estônia', '🇪🇪', 'Europa', 'Tallinn', 'Estoniano', '1571'),
('FI', 'Finlândia', '🇫🇮', 'Europa', 'Helsinque', 'Finlandês', '1619'),
('FR', 'França', '🇫🇷', 'Europa', 'Paris', 'Francês', '1635'),
('GR', 'Grécia', '🇬🇷', 'Europa', 'Atenas', 'Grego', '1732'),
('NL', 'Holanda', '🇳🇱', 'Europa', 'Amsterdã', 'Holandês', '1937'),
('HU', 'Hungria', '🇭🇺', 'Europa', 'Budapeste', 'Húngaro', '1953'),
('IE', 'Irlanda', '🇮🇪', 'Europa', 'Dublin', 'Irlandês/Inglês', '2399'),
('IS', 'Islândia', '🇮🇸', 'Europa', 'Reykjavik', 'Islandês', '2445'),
('IT', 'Itália', '🇮🇹', 'Europa', 'Roma', 'Italiano', '2453'),
('LV', 'Letônia', '🇱🇻', 'Europa', 'Riga', 'Letão', '2470'),
('LT', 'Lituânia', '🇱🇹', 'Europa', 'Vilnius', 'Lituano', '2461'),
('LU', 'Luxemburgo', '🇱🇺', 'Europa', 'Luxemburgo', 'Luxemburguês', '2518'),
('MT', 'Malta', '🇲🇹', 'Europa', 'Valeta', 'Maltês/Inglês', '2585'),
('NO', 'Noruega', '🇳🇴', 'Europa', 'Oslo', 'Norueguês', '2470'),
('PL', 'Polônia', '🇵🇱', 'Europa', 'Varsóvia', 'Polonês', '2321'),
('PT', 'Portugal', '🇵🇹', 'Europa', 'Lisboa', 'Português', '2330'),
('GB', 'Reino Unido', '🇬🇧', 'Europa', 'Londres', 'Inglês', '2470'),
('CZ', 'República Tcheca', '🇨🇿', 'Europa', 'Praga', 'Tcheco', '1414'),
('RO', 'Romênia', '🇷🇴', 'Europa', 'Bucareste', 'Romeno', '2429'),
('RU', 'Rússia', '🇷🇺', 'Europa/Ásia', 'Moscou', 'Russo', '2437'),
('SE', 'Suécia', '🇸🇪', 'Europa', 'Estocolmo', 'Sueco', '2615'),
('CH', 'Suíça', '🇨🇭', 'Europa', 'Berna', 'Alemão/Francês/Italiano', '2623'),
('UA', 'Ucrânia', '🇺🇦', 'Europa', 'Kiev', 'Ucraniano', '2674')
ON CONFLICT (code) DO NOTHING;

-- Inserir países da Ásia
INSERT INTO countries (code, name, flag, continent, capital, language, bacen_code) VALUES
('AF', 'Afeganistão', '🇦🇫', 'Ásia', 'Cabul', 'Pashto/Dari', '0132'),
('SA', 'Arábia Saudita', '🇸🇦', 'Ásia', 'Riad', 'Árabe', '0531'),
('AM', 'Armênia', '🇦🇲', 'Ásia', 'Yerevan', 'Armênio', '0396'),
('AZ', 'Azerbaijão', '🇦🇿', 'Ásia', 'Baku', 'Azerbaijano', '0450'),
('BH', 'Bahrein', '🇧🇭', 'Ásia', 'Manama', 'Árabe', '0809'),
('BD', 'Bangladesh', '🇧🇩', 'Ásia', 'Dhaka', 'Bengali', '0825'),
('MM', 'Birmânia', '🇲🇲', 'Ásia', 'Naypyidaw', 'Birmanês', '0310'),
('BN', 'Brunei', '🇧🇳', 'Ásia', 'Bandar Seri Begawan', 'Malaio', '1074'),
('BT', 'Butão', '🇧🇹', 'Ásia', 'Thimphu', 'Dzonga', '1112'),
('KH', 'Camboja', '🇰🇭', 'Ásia', 'Phnom Penh', 'Khmer', '1155'),
('KZ', 'Cazaquistão', '🇰🇿', 'Ásia', 'Astana', 'Cazaque/Russo', '1376'),
('CN', 'China', '🇨🇳', 'Ásia', 'Pequim', 'Mandarim', '1210'),
('CY', 'Chipre', '🇨🇾', 'Ásia', 'Nicósia', 'Grego/Turco', '1494'),
('KP', 'Coreia do Norte', '🇰🇵', 'Ásia', 'Pyongyang', 'Coreano', '1732'),
('KR', 'Coreia do Sul', '🇰🇷', 'Ásia', 'Seul', 'Coreano', '1864'),
('AE', 'Emirados Árabes', '🇦🇪', 'Ásia', 'Abu Dhabi', 'Árabe', '2445'),
('PH', 'Filipinas', '🇵🇭', 'Ásia', 'Manila', 'Filipino/Inglês', '1651'),
('GE', 'Geórgia', '🇬🇪', 'Ásia', 'Tbilisi', 'Georgiano', '1694'),
('IN', 'Índia', '🇮🇳', 'Ásia', 'Nova Delhi', 'Hindi/Inglês', '1988'),
('ID', 'Indonésia', '🇮🇩', 'Ásia', 'Jacarta', 'Indonésio', '2011'),
('IQ', 'Iraque', '🇮🇶', 'Ásia', 'Bagdá', 'Árabe/Curdo', '2402'),
('IR', 'Irã', '🇮🇷', 'Ásia', 'Teerã', 'Persa', '2410'),
('IL', 'Israel', '🇮🇱', 'Ásia', 'Jerusalém', 'Hebraico/Árabe', '2429'),
('JP', 'Japão', '🇯🇵', 'Ásia', 'Tóquio', 'Japonês', '2518'),
('JO', 'Jordânia', '🇯🇴', 'Ásia', 'Amã', 'Árabe', '2526'),
('KW', 'Kuwait', '🇰🇼', 'Ásia', 'Cidade do Kuwait', 'Árabe', '1872'),
('LA', 'Laos', '🇱🇦', 'Ásia', 'Vientiane', 'Lao', '1902'),
('LB', 'Líbano', '🇱🇧', 'Ásia', 'Beirute', 'Árabe', '1910'),
('MY', 'Malásia', '🇲🇾', 'Ásia', 'Kuala Lumpur', 'Malaio', '2534'),
('MV', 'Maldivas', '🇲🇻', 'Ásia', 'Malé', 'Dhivehi', '2550'),
('MN', 'Mongólia', '🇲🇳', 'Ásia', 'Ulaanbaatar', 'Mongol', '2593'),
('NP', 'Nepal', '🇳🇵', 'Ásia', 'Katmandu', 'Nepalês', '2674'),
('OM', 'Omã', '🇴🇲', 'Ásia', 'Mascate', 'Árabe', '2119'),
('PK', 'Paquistão', '🇵🇰', 'Ásia', 'Islamabad', 'Urdu/Inglês', '2291'),
('QA', 'Qatar', '🇶🇦', 'Ásia', 'Doha', 'Árabe', '2399'),
('KG', 'Quirguistão', '🇰🇬', 'Ásia', 'Bishkek', 'Quirguiz', '1848'),
('SG', 'Singapura', '🇸🇬', 'Ásia', 'Singapura', 'Inglês/Malaio/Mandarim', '2470'),
('SY', 'Síria', '🇸🇾', 'Ásia', 'Damasco', 'Árabe', '2640'),
('LK', 'Sri Lanka', '🇱🇰', 'Ásia', 'Colombo', 'Cingalês/Tâmil', '2445'),
('TJ', 'Tajiquistão', '🇹🇯', 'Ásia', 'Dushanbe', 'Tajique', '2658'),
('TH', 'Tailândia', '🇹🇭', 'Ásia', 'Bangkok', 'Tailandês', '2674'),
('TL', 'Timor-Leste', '🇹🇱', 'Ásia', 'Dili', 'Tétum/Português', '7919'),
('TR', 'Turquia', '🇹🇷', 'Ásia/Europa', 'Ancara', 'Turco', '2712'),
('TM', 'Turcomenistão', '🇹🇲', 'Ásia', 'Ashgabat', 'Turcomeno', '2704'),
('UZ', 'Uzbequistão', '🇺🇿', 'Ásia', 'Tashkent', 'Uzbeque', '2720'),
('VN', 'Vietnã', '🇻🇳', 'Ásia', 'Hanói', 'Vietnamita', '2755'),
('YE', 'Iêmen', '🇾🇪', 'Ásia', 'Sanaa', 'Árabe', '1996')
ON CONFLICT (code) DO NOTHING;

-- Inserir países da África
INSERT INTO countries (code, name, flag, continent, capital, language, bacen_code) VALUES
('ZA', 'África do Sul', '🇿🇦', 'África', 'Pretória', 'Inglês/Africâner', '7560'),
('DZ', 'Argélia', '🇩🇿', 'África', 'Argel', 'Árabe', '0370'),
('AO', 'Angola', '🇦🇴', 'África', 'Luanda', 'Português', '0310'),
('BJ', 'Benin', '🇧🇯', 'África', 'Porto Novo', 'Francês', '0973'),
('BW', 'Botsuana', '🇧🇼', 'África', 'Gaborone', 'Inglês', '1040'),
('BF', 'Burkina Faso', '🇧🇫', 'África', 'Ouagadougou', 'Francês', '0310'),
('BI', 'Burundi', '🇧🇮', 'África', 'Gitega', 'Francês/Kirundi', '1120'),
('CM', 'Camarões', '🇨🇲', 'África', 'Yaoundé', 'Francês/Inglês', '1163'),
('CV', 'Cabo Verde', '🇨🇻', 'África', 'Praia', 'Português', '1490'),
('TD', 'Chade', '🇹🇩', 'África', 'N\'Djamena', 'Francês/Árabe', '2682'),
('KM', 'Comores', '🇰🇲', 'África', 'Moroni', 'Árabe/Francês', '1350'),
('CG', 'Congo', '🇨🇬', 'África', 'Brazzaville', 'Francês', '1457'),
('CD', 'Congo (RD)', '🇨🇩', 'África', 'Kinshasa', 'Francês', '8885'),
('CI', 'Costa do Marfim', '🇨🇮', 'África', 'Yamoussoukro', 'Francês', '1384'),
('DJ', 'Djibuti', '🇩🇯', 'África', 'Djibuti', 'Francês/Árabe', '1465'),
('EG', 'Egito', '🇪🇬', 'África', 'Cairo', 'Árabe', '1508'),
('ER', 'Eritreia', '🇪🇷', 'África', 'Asmara', 'Tigrínia', '1589'),
('ET', 'Etiópia', '🇪🇹', 'África', 'Adis Abeba', 'Amárico', '1600'),
('GA', 'Gabão', '🇬🇦', 'África', 'Libreville', 'Francês', '1651'),
('GM', 'Gâmbia', '🇬🇲', 'África', 'Banjul', 'Inglês', '1678'),
('GH', 'Gana', '🇬🇭', 'África', 'Acra', 'Inglês', '1686'),
('GN', 'Guiné', '🇬🇳', 'África', 'Conacri', 'Francês', '3595'),
('GW', 'Guiné-Bissau', '🇬🇼', 'África', 'Bissau', 'Português', '3603'),
('GQ', 'Guiné Equatorial', '🇬🇶', 'África', 'Malabo', 'Espanhol/Francês', '3611'),
('KE', 'Quênia', '🇰🇪', 'África', 'Nairóbi', 'Inglês/Suaíli', '1830'),
('LS', 'Lesoto', '🇱🇸', 'África', 'Maseru', 'Inglês/Sesoto', '1902'),
('LR', 'Libéria', '🇱🇷', 'África', 'Monróvia', 'Inglês', '1929'),
('LY', 'Líbia', '🇱🇾', 'África', 'Trípoli', 'Árabe', '1945'),
('MG', 'Madagascar', '🇲🇬', 'África', 'Antananarivo', 'Malgaxe/Francês', '3999'),
('MW', 'Malawi', '🇲🇼', 'África', 'Lilongwe', 'Inglês', '2542'),
('ML', 'Mali', '🇲🇱', 'África', 'Bamako', 'Francês', '2577'),
('MA', 'Marrocos', '🇲🇦', 'África', 'Rabat', 'Árabe', '2607'),
('MU', 'Maurício', '🇲🇺', 'África', 'Port Louis', 'Inglês', '2615'),
('MR', 'Mauritânia', '🇲🇷', 'África', 'Nouakchott', 'Árabe', '2623'),
('MZ', 'Moçambique', '🇲🇿', 'África', 'Maputo', 'Português', '2658'),
('NA', 'Namíbia', '🇳🇦', 'África', 'Windhoek', 'Inglês', '2674'),
('NE', 'Níger', '🇳🇪', 'África', 'Niamey', 'Francês', '1945'),
('NG', 'Nigéria', '🇳🇬', 'África', 'Abuja', 'Inglês', '2704'),
('CF', 'República Centro-Africana', '🇨🇫', 'África', 'Bangui', 'Francês', '1414'),
('RW', 'Ruanda', '🇷🇼', 'África', 'Kigali', 'Kinyarwanda/Francês/Inglês', '2437'),
('ST', 'São Tomé e Príncipe', '🇸🇹', 'África', 'São Tomé', 'Português', '2682'),
('SN', 'Senegal', '🇸🇳', 'África', 'Dakar', 'Francês', '2712'),
('SC', 'Seicheles', '🇸🇨', 'África', 'Victoria', 'Inglês/Francês', '7889'),
('SL', 'Serra Leoa', '🇸🇱', 'África', 'Freetown', 'Inglês', '2720'),
('SO', 'Somália', '🇸🇴', 'África', 'Mogadíscio', 'Somali/Árabe', '2755'),
('SD', 'Sudão', '🇸🇩', 'África', 'Cartum', 'Árabe', '7412'),
('SS', 'Sudão do Sul', '🇸🇸', 'África', 'Juba', 'Inglês', '7765'),
('SZ', 'Eswatini', '🇸🇿', 'África', 'Mbabane', 'Inglês/Suázi', '7838'),
('TZ', 'Tanzânia', '🇹🇿', 'África', 'Dodoma', 'Suaíli/Inglês', '7722'),
('TG', 'Togo', '🇹🇬', 'África', 'Lomé', 'Francês', '2690'),
('TN', 'Tunísia', '🇹🇳', 'África', 'Túnis', 'Árabe', '2747'),
('UG', 'Uganda', '🇺🇬', 'África', 'Kampala', 'Inglês', '7838'),
('ZM', 'Zâmbia', '🇿🇲', 'África', 'Lusaka', 'Inglês', '7838'),
('ZW', 'Zimbábue', '🇿🇼', 'África', 'Harare', 'Inglês', '2909')
ON CONFLICT (code) DO NOTHING;

-- Inserir países da América do Sul (complementar aos já existentes)
INSERT INTO countries (code, name, flag, continent, capital, language, bacen_code) VALUES
('BO', 'Bolívia', '🇧🇴', 'América do Sul', 'Sucre', 'Espanhol', '1023'),
('GY', 'Guiana', '🇬🇾', 'América do Sul', 'Georgetown', 'Inglês', '3379'),
('GF', 'Guiana Francesa', '🇬🇫', 'América do Sul', 'Caiena', 'Francês', '3363'),
('PY', 'Paraguai', '🇵🇾', 'América do Sul', 'Assunção', 'Espanhol/Guarani', '2267'),
('SR', 'Suriname', '🇸🇷', 'América do Sul', 'Paramaribo', 'Holandês', '2763'),
('UY', 'Uruguai', '🇺🇾', 'América do Sul', 'Montevidéu', 'Espanhol', '7370')
ON CONFLICT (code) DO NOTHING;

-- Inserir países da América Central e Caribe
INSERT INTO countries (code, name, flag, continent, capital, language, bacen_code) VALUES
('AG', 'Antígua e Barbuda', '🇦🇬', 'América Central', 'Saint John\'s', 'Inglês', '0337'),
('BS', 'Bahamas', '🇧🇸', 'América Central', 'Nassau', 'Inglês', '0655'),
('BB', 'Barbados', '🇧🇧', 'América Central', 'Bridgetown', 'Inglês', '0850'),
('BZ', 'Belize', '🇧🇿', 'América Central', 'Belmopan', 'Inglês', '0965'),
('CR', 'Costa Rica', '🇨🇷', 'América Central', 'San José', 'Espanhol', '1449'),
('CU', 'Cuba', '🇨🇺', 'América Central', 'Havana', 'Espanhol', '1511'),
('DM', 'Dominica', '🇩🇲', 'América Central', 'Roseau', 'Inglês', '1473'),
('DO', 'República Dominicana', '🇩🇴', 'América Central', 'Santo Domingo', 'Espanhol', '6874'),
('SV', 'El Salvador', '🇸🇻', 'América Central', 'San Salvador', 'Espanhol', '6858'),
('GD', 'Granada', '🇬🇩', 'América Central', 'Saint George\'s', 'Inglês', '1716'),
('GT', 'Guatemala', '🇬🇹', 'América Central', 'Cidade da Guatemala', 'Espanhol', '1767'),
('HT', 'Haiti', '🇭🇹', 'América Central', 'Porto Príncipe', 'Francês/Crioulo', '1830'),
('HN', 'Honduras', '🇭🇳', 'América Central', 'Tegucigalpa', 'Espanhol', '1945'),
('JM', 'Jamaica', '🇯🇲', 'América Central', 'Kingston', 'Inglês', '2496'),
('NI', 'Nicarágua', '🇳🇮', 'América Central', 'Manágua', 'Espanhol', '2399'),
('PA', 'Panamá', '🇵🇦', 'América Central', 'Cidade do Panamá', 'Espanhol', '2186'),
('KN', 'São Cristóvão e Névis', '🇰🇳', 'América Central', 'Basseterre', 'Inglês', '6289'),
('LC', 'Santa Lúcia', '🇱🇨', 'América Central', 'Castries', 'Inglês', '6408'),
('VC', 'São Vicente e Granadinas', '🇻🇨', 'América Central', 'Kingstown', 'Inglês', '6659'),
('TT', 'Trinidad e Tobago', '🇹🇹', 'América Central', 'Port of Spain', 'Inglês', '2780')
ON CONFLICT (code) DO NOTHING;

-- Inserir países da Oceania
INSERT INTO countries (code, name, flag, continent, capital, language, bacen_code) VALUES
('AU', 'Austrália', '🇦🇺', 'Oceania', 'Camberra', 'Inglês', '0611'),
('FJ', 'Fiji', '🇫🇯', 'Oceania', 'Suva', 'Inglês/Fijiano', '1635'),
('KI', 'Kiribati', '🇰🇮', 'Oceania', 'Tarawa', 'Inglês', '1842'),
('MH', 'Ilhas Marshall', '🇲🇭', 'Oceania', 'Majuro', 'Inglês/Marshalês', '4985'),
('FM', 'Micronésia', '🇫🇲', 'Oceania', 'Palikir', 'Inglês', '5053'),
('NR', 'Nauru', '🇳🇷', 'Oceania', 'Yaren', 'Inglês/Nauruano', '5738'),
('NZ', 'Nova Zelândia', '🇳🇿', 'Oceania', 'Wellington', 'Inglês/Maori', '5487'),
('PW', 'Palau', '🇵🇼', 'Oceania', 'Ngerulmud', 'Inglês/Palauano', '5754'),
('PG', 'Papua Nova Guiné', '🇵🇬', 'Oceania', 'Port Moresby', 'Inglês', '2283'),
('WS', 'Samoa', '🇼🇸', 'Oceania', 'Apia', 'Samoano/Inglês', '6475'),
('SB', 'Ilhas Salomão', '🇸🇧', 'Oceania', 'Honiara', 'Inglês', '3247'),
('TO', 'Tonga', '🇹🇴', 'Oceania', 'Nuku\'alofa', 'Inglês/Tonganês', '2798'),
('TV', 'Tuvalu', '🇹🇻', 'Oceania', 'Funafuti', 'Inglês/Tuvaluano', '7838'),
('VU', 'Vanuatu', '🇻🇺', 'Oceania', 'Port Vila', 'Inglês/Francês', '5991')
ON CONFLICT (code) DO NOTHING;
