import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const localesDir = path.join(__dirname, '../src/locales');

const newTranslationsPt = {
  carriers: {
    vision360: {
      aiInsight: {
        title: "Insight IA",
        subtitle: "Análise inteligente para {{carrierName}}",
        generating: "Gerando análise inteligente...",
        generatedTitle: "Análise Gerada por IA",
        warning: "Esta análise foi gerada por inteligência artificial e deve ser usada como referência. Sempre valide as informações com dados reais antes de tomar decisões.",
        errorTitle: "Não foi possível gerar a análise. Tente novamente.",
        close: "Fechar",
        notContractedError: "Recurso não contratado. Ative em Inovações & Sugestões.",
        notContractedNotice: "Integração com OpenAI/ChatGPT não contratada:",
        notContractedDesc1: "Para utilizar o botão de inteligência artificial \"Insight IA\", é necessário ativar o serviço em",
        notContractedDesc2: "Inovações & Sugestões",
        notContractedDesc3: ". Sem a ativação, o botão não terão efeito."
      },
      kpi: {
        totalDeliveries: "Total de Entregas",
        vsLastMonth: "+12% vs mês anterior",
        inTransit: "Em Trânsito",
        percentOfTotal: "{{percent}}% do total",
        deliveredToday: "Entregue Hoje",
        goalPerDay: "Meta: 45/dia",
        delayed: "Atrasadas",
        awaitingPickup: "Aguardando Coleta",
        prioritizePickups: "Priorizar coletas",
        punctualityRate: "Taxa de Pontualidade",
        aboveGoal: "Acima da meta (90%)"
      },
      charts: {
        deliveryStatus: "Status das Entregas",
        weeklyPerformance: "Desempenho Semanal",
        monthlyTrend: "Tendência de Entregas (Últimos 6 Meses)",
        deliveries: "Entregas",
        punctualityPercent: "Pontualidade %",
        totalDeliveries: "Total de Entregas"
      },
      filters: {
        period: "Período:",
        to: "até",
        refresh: "Atualizar",
        aiInsightBtn: "Insight IA"
      },
      status: {
        delivered: "Entregue",
        inTransit: "Em Trânsito",
        delayed: "Atrasado",
        awaiting: "Aguardando"
      },
      days: {
        mon: "Seg",
        tue: "Ter",
        wed: "Qua",
        thu: "Qui",
        fri: "Sex",
        sat: "Sáb",
        sun: "Dom"
      },
      months: {
        jan: "Jan",
        feb: "Fev",
        mar: "Mar",
        apr: "Abr",
        may: "Mai",
        jun: "Jun"
      }
    }
  }
};

const newTranslationsEn = {
  carriers: {
    vision360: {
      aiInsight: {
        title: "AI Insight",
        subtitle: "Intelligent analysis for {{carrierName}}",
        generating: "Generating intelligent analysis...",
        generatedTitle: "AI-Generated Analysis",
        warning: "This analysis was generated by artificial intelligence and should be used as a reference. Always validate information with real data before making decisions.",
        errorTitle: "Could not generate analysis. Please try again.",
        close: "Close",
        notContractedError: "Feature not contracted. Activate in Innovations & Suggestions.",
        notContractedNotice: "OpenAI/ChatGPT integration not contracted:",
        notContractedDesc1: "To use the \"AI Insight\" button, you must activate the service in",
        notContractedDesc2: "Innovations & Suggestions",
        notContractedDesc3: ". Without activation, the button will have no effect."
      },
      kpi: {
        totalDeliveries: "Total Deliveries",
        vsLastMonth: "+12% vs last month",
        inTransit: "In Transit",
        percentOfTotal: "{{percent}}% of total",
        deliveredToday: "Delivered Today",
        goalPerDay: "Goal: 45/day",
        delayed: "Delayed",
        awaitingPickup: "Awaiting Pickup",
        prioritizePickups: "Prioritize pickups",
        punctualityRate: "Punctuality Rate",
        aboveGoal: "Above goal (90%)"
      },
      charts: {
        deliveryStatus: "Delivery Status",
        weeklyPerformance: "Weekly Performance",
        monthlyTrend: "Delivery Trend (Last 6 Months)",
        deliveries: "Deliveries",
        punctualityPercent: "Punctuality %",
        totalDeliveries: "Total Deliveries"
      },
      filters: {
        period: "Period:",
        to: "to",
        refresh: "Refresh",
        aiInsightBtn: "AI Insight"
      },
      status: {
        delivered: "Delivered",
        inTransit: "In Transit",
        delayed: "Delayed",
        awaiting: "Awaiting"
      },
      days: {
        mon: "Mon",
        tue: "Tue",
        wed: "Wed",
        thu: "Thu",
        fri: "Fri",
        sat: "Sat",
        sun: "Sun"
      },
      months: {
        jan: "Jan",
        feb: "Feb",
        mar: "Mar",
        apr: "Apr",
        may: "May",
        jun: "Jun"
      }
    }
  }
};

const newTranslationsEs = {
  carriers: {
    vision360: {
      aiInsight: {
        title: "Insight de IA",
        subtitle: "Análisis inteligente para {{carrierName}}",
        generating: "Generando análisis inteligente...",
        generatedTitle: "Análisis Generado por IA",
        warning: "Este análisis fue generado por inteligencia artificial y debe usarse como referencia. Siempre valide la información con datos reales antes de tomar decisiones.",
        errorTitle: "No se pudo generar el análisis. Inténtelo de nuevo.",
        close: "Cerrar",
        notContractedError: "Característica no contratada. Actívela en Innovaciones y Sugerencias.",
        notContractedNotice: "Integración de OpenAI/ChatGPT no contratada:",
        notContractedDesc1: "Para usar el botón \"Insight de IA\", debe activar el servicio en",
        notContractedDesc2: "Innovaciones y Sugerencias",
        notContractedDesc3: ". Sin activación, el botón no tendrá efecto."
      },
      kpi: {
        totalDeliveries: "Total de Entregas",
        vsLastMonth: "+12% vs mes anterior",
        inTransit: "En Tránsito",
        percentOfTotal: "{{percent}}% del total",
        deliveredToday: "Entregadas Hoy",
        goalPerDay: "Meta: 45/día",
        delayed: "Retrasadas",
        awaitingPickup: "Esperando Recogida",
        prioritizePickups: "Priorizar recogidas",
        punctualityRate: "Tasa de Puntualidad",
        aboveGoal: "Por encima de la meta (90%)"
      },
      charts: {
        deliveryStatus: "Estado de las Entregas",
        weeklyPerformance: "Rendimiento Semanal",
        monthlyTrend: "Tendencia de Entregas (Últimos 6 Meses)",
        deliveries: "Entregas",
        punctualityPercent: "Puntualidad %",
        totalDeliveries: "Total de Entregas"
      },
      filters: {
        period: "Período:",
        to: "hasta",
        refresh: "Actualizar",
        aiInsightBtn: "Insight de IA"
      },
      status: {
        delivered: "Entregada",
        inTransit: "En Tránsito",
        delayed: "Retrasada",
        awaiting: "Esperando"
      },
      days: {
        mon: "Lun",
        tue: "Mar",
        wed: "Mié",
        thu: "Jue",
        fri: "Vie",
        sat: "Sáb",
        sun: "Dom"
      },
      months: {
        jan: "Ene",
        feb: "Feb",
        mar: "Mar",
        apr: "Abr",
        may: "May",
        jun: "Jun"
      }
    }
  }
};

const langs = [
  { code: 'pt', ext: newTranslationsPt },
  { code: 'en', ext: newTranslationsEn },
  { code: 'es', ext: newTranslationsEs }
];

function isObject(item) {
  return (item && typeof item === 'object' && !Array.isArray(item));
}

function deepMergeLocal(target, source) {
  if (isObject(target) && isObject(source)) {
    for (const key in source) {
      if (isObject(source[key])) {
        if (!target[key]) Object.assign(target, { [key]: {} });
        deepMergeLocal(target[key], source[key]);
      } else {
        Object.assign(target, { [key]: source[key] });
      }
    }
  }
  return target;
}

langs.forEach(({ code, ext }) => {
  const filePath = path.join(localesDir, code, 'translation.json');
  const fileContent = fs.readFileSync(filePath, 'utf-8');
  const fileJson = JSON.parse(fileContent);
  
  if (!fileJson.carriers) fileJson.carriers = {};
  if (!fileJson.carriers.vision360) fileJson.carriers.vision360 = {};
  
  fileJson.carriers.vision360 = deepMergeLocal(fileJson.carriers.vision360, ext.carriers.vision360);
  
  fs.writeFileSync(filePath, JSON.stringify(fileJson, null, 2), 'utf-8');
});

console.log('Translations for CarrierVision360 merged successfully.');
