import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const localesDir = path.resolve(__dirname, '../src/locales');
const languages = ['pt', 'en', 'es'];

const translations = {
  pt: {
    vision360: {
      aiInsight: {
        title: "Insight IA",
        subtitle: "Análise inteligente para {{name}} ({{type}})",
        generating: "Gerando análise inteligente...",
        aiAnalysisGenerated: "Análise Gerada por IA",
        warning: "Esta análise foi gerada por inteligência artificial e deve ser usada como referência. Sempre valide as informações com dados reais antes de tomar decisões.",
        error: "Não foi possível gerar a análise. Tente novamente.",
        close: "Fechar",
        notHired: "Integração com OpenAI/ChatGPT não contratada",
        notHiredDesc: "Para utilizar o botão de inteligência artificial \"Insight IA\", é necessário ativar o serviço em **Inovações & Sugestões**. Sem a ativação, o botão não terão efeito.",
        notHiredToast: "Recurso não contratado. Ative em Inovações & Sugestões."
      },
      filters: {
        period: "Período:",
        until: "até",
        refresh: "Atualizar",
        aiInsightBtn: "Insight IA"
      },
      kpis: {
        orders: "Pedidos",
        ordersSub: "+8% vs mês anterior",
        invoices: "Notas Fiscais",
        invoicesSub: "{{percent}}% dos pedidos",
        pickups: "Coletas",
        pickupsSub: "Média: 52/mês",
        ctes: "CT-e",
        ctesSub: "{{percent}}% das NF-e",
        bills: "Faturas",
        billsSub: "Média: R$ 5.172,00",
        deliveriesCompleted: "Entregas Realizadas",
        deliveriesCompletedSub: "{{percent}}% do total",
        deliveriesPending: "Entregas Pendentes",
        deliveriesPendingSub: "Monitorar prazos"
      },
      charts: {
        documentDistribution: "Distribuição de Documentos",
        deliveryStatus: "Status de Entregas",
        weeklyActivity: "Atividade Semanal",
        pickupTrend: "Tendência de Coletas",
        monthlyEvolution: "Evolução Mensal - Volume e Valor"
      },
      chartData: {
        orders: "Pedidos",
        invoices: "Notas Fiscais",
        ctes: "CT-e",
        bills: "Faturas",
        completed: "Concluídas",
        pending: "Pendentes",
        deliveries: "Entregas",
        pickups: "Coletas",
        volume: "Volume de Operações",
        value: "Valor (R$)"
      },
      weekDays: {
        mon: "Seg",
        tue: "Ter",
        wed: "Qua",
        thu: "Qui",
        fri: "Sex",
        sat: "Sáb",
        sun: "Dom"
      },
      months: {
        jan: "Jan",
        feb: "Fev",
        mar: "Mar",
        apr: "Abr",
        may: "Mai",
        jun: "Jun"
      }
    }
  },
  en: {
    vision360: {
      aiInsight: {
        title: "AI Insight",
        subtitle: "Intelligent analysis for {{name}} ({{type}})",
        generating: "Generating intelligent analysis...",
        aiAnalysisGenerated: "AI Generated Analysis",
        warning: "This analysis was generated by artificial intelligence and should be used as a reference. Always validate information with real data before making decisions.",
        error: "Could not generate analysis. Please try again.",
        close: "Close",
        notHired: "OpenAI/ChatGPT integration not hired",
        notHiredDesc: "To use the artificial intelligence button \"AI Insight\", you must activate the service in **Innovations & Suggestions**. Without activation, the button will have no effect.",
        notHiredToast: "Feature not hired. Activate in Innovations & Suggestions."
      },
      filters: {
        period: "Period:",
        until: "until",
        refresh: "Refresh",
        aiInsightBtn: "AI Insight"
      },
      kpis: {
        orders: "Orders",
        ordersSub: "+8% vs previous month",
        invoices: "Invoices",
        invoicesSub: "{{percent}}% of orders",
        pickups: "Pickups",
        pickupsSub: "Average: 52/month",
        ctes: "CT-e",
        ctesSub: "{{percent}}% of invoices",
        bills: "Bills",
        billsSub: "Average: $ 5,172.00",
        deliveriesCompleted: "Completed Deliveries",
        deliveriesCompletedSub: "{{percent}}% of total",
        deliveriesPending: "Pending Deliveries",
        deliveriesPendingSub: "Monitor deadlines"
      },
      charts: {
        documentDistribution: "Document Distribution",
        deliveryStatus: "Delivery Status",
        weeklyActivity: "Weekly Activity",
        pickupTrend: "Pickup Trend",
        monthlyEvolution: "Monthly Evolution - Volume and Value"
      },
      chartData: {
        orders: "Orders",
        invoices: "Invoices",
        ctes: "CT-e",
        bills: "Bills",
        completed: "Completed",
        pending: "Pending",
        deliveries: "Deliveries",
        pickups: "Pickups",
        volume: "Operation Volume",
        value: "Value ($)"
      },
      weekDays: {
        mon: "Mon",
        tue: "Tue",
        wed: "Wed",
        thu: "Thu",
        fri: "Fri",
        sat: "Sat",
        sun: "Sun"
      },
      months: {
        jan: "Jan",
        feb: "Feb",
        mar: "Mar",
        apr: "Apr",
        may: "May",
        jun: "Jun"
      }
    }
  },
  es: {
    vision360: {
      aiInsight: {
        title: "Insight IA",
        subtitle: "Análisis inteligente para {{name}} ({{type}})",
        generating: "Generando análisis inteligente...",
        aiAnalysisGenerated: "Análisis Generado por IA",
        warning: "Este análisis fue generado por inteligencia artificial y debe usarse como referencia. Siempre valide la información con datos reales antes de tomar decisiones.",
        error: "No se pudo generar el análisis. Inténtelo de nuevo.",
        close: "Cerrar",
        notHired: "Integración con OpenAI/ChatGPT no contratada",
        notHiredDesc: "Para utilizar el botón de inteligencia artificial \"Insight IA\", debe activar el servicio en **Innovaciones y Sugerencias**. Sin activación, el botón no tendrá efecto.",
        notHiredToast: "Función no contratada. Active en Innovaciones y Sugerencias."
      },
      filters: {
        period: "Periodo:",
        until: "hasta",
        refresh: "Actualizar",
        aiInsightBtn: "Insight IA"
      },
      kpis: {
        orders: "Pedidos",
        ordersSub: "+8% vs mes anterior",
        invoices: "Facturas",
        invoicesSub: "{{percent}}% de pedidos",
        pickups: "Recogidas",
        pickupsSub: "Promedio: 52/mes",
        ctes: "CT-e",
        ctesSub: "{{percent}}% de facturas",
        bills: "Pagos",
        billsSub: "Promedio: € 5.172,00",
        deliveriesCompleted: "Entregas Completadas",
        deliveriesCompletedSub: "{{percent}}% del total",
        deliveriesPending: "Entregas Pendientes",
        deliveriesPendingSub: "Monitorear plazos"
      },
      charts: {
        documentDistribution: "Distribución de Documentos",
        deliveryStatus: "Estado de Entregas",
        weeklyActivity: "Actividad Semanal",
        pickupTrend: "Tendencia de Recogidas",
        monthlyEvolution: "Evolución Mensual - Volumen y Valor"
      },
      chartData: {
        orders: "Pedidos",
        invoices: "Facturas",
        ctes: "CT-e",
        bills: "Pagos",
        completed: "Completadas",
        pending: "Pendientes",
        deliveries: "Entregas",
        pickups: "Recogidas",
        volume: "Volumen de Operaciones",
        value: "Valor (€)"
      },
      weekDays: {
        mon: "Lun",
        tue: "Mar",
        wed: "Mié",
        thu: "Jue",
        fri: "Vie",
        sat: "Sáb",
        sun: "Dom"
      },
      months: {
        jan: "Ene",
        feb: "Feb",
        mar: "Mar",
        apr: "Abr",
        may: "May",
        jun: "Jun"
      }
    }
  }
};

languages.forEach(lang => {
  const filePath = path.join(localesDir, lang, 'translation.json');
  if (fs.existsSync(filePath)) {
    const fileContent = fs.readFileSync(filePath, 'utf8');
    const json = JSON.parse(fileContent);
    
    // Initialise if not exists
    if (!json.businessPartners) {
      json.businessPartners = {};
    }

    json.businessPartners.vision360 = {
      ...(json.businessPartners.vision360 || {}),
      ...translations[lang].vision360
    };

    fs.writeFileSync(filePath, JSON.stringify(json, null, 2), 'utf8');
    console.log(`Updated vision360 translations for ${lang}`);
  } else {
    console.error(`File not found: ${filePath}`);
  }
});
