const fs = require('fs');

let c = fs.readFileSync('tms-erp-proxy/services/auto-import/index.js', 'utf8');

// Remove any broken Deno imports that might be left
c = c.replace(/import \{ serve \} from ".*?;/, '');
c = c.replace(/import \{ createClient \} from ".*?;/, 'import { createClient } from "@supabase/supabase-js";');

// Also remove Deno import from the second line if it exists
c = c.replace(/import \{ serve \} from '.*?;/, '');

// Fix mixed quotes generated by the previous bad replacement
c = c.replace(/import \{ calculateBestFreight, calculateCteFreight \} from "\.\/freightQuoter\.js';/, 'import { calculateBestFreight, calculateCteFreight } from "./freightQuoter.js";');
c = c.replace(/import \{ processDoccobExtracted \} from "\.\/doccobImporter\.js';/, 'import { processDoccobExtracted } from "./doccobImporter.js";');

fs.writeFileSync('tms-erp-proxy/services/auto-import/index.js', c);
